# Generated by Django 5.1.5 on 2025-01-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('datetimes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.datetimes')),
                ('delivery_method', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=355)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=150)),
                ('cart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.cart')),
            ],
            bases=('blog.datetimes',),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('datetimes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.datetimes')),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('click pay', 'Click Pay')], max_length=150)),
                ('screenshot_url', models.CharField(max_length=150)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.orders')),
            ],
            bases=('blog.datetimes',),
        ),
    ]
